# Generated by Django 5.2 on 2025-05-03 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_initial'),
        ('recommendations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='articles.article'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='score',
            field=models.FloatField(help_text='Puntuación de relevancia entre 0 y 1'),
        ),
    ]
