# Generated by Django 5.2 on 2025-05-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_tag_name_alter_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_destination',
            field=models.BooleanField(default=False, help_text='Indica si este artículo debe ser tratado como un destino'),
        ),
    ]
