# Generated by Django 5.2 on 2025-05-04 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_is_destination'),
        ('destinations', '0002_continent_destination_continent'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='continent',
            field=models.ForeignKey(blank=True, help_text='Continente al que pertenece este artículo si es un destino', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='destinations.continent'),
        ),
    ]
