# Generated by Django 5.2 on 2025-04-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_initial'),
        ('users', '0003_remove_profile_interests_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(related_name='users_interested', to='articles.tag'),
        ),
    ]
