# Generated by Django 5.2 on 2025-05-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('reader', 'Lector'), ('content_creator', 'Creador de Contenido'), ('admin', 'Administrador')], default='reader', help_text='Rol del usuario que determina sus permisos en la plataforma', max_length=20),
        ),
    ]
