# Generated by Django 5.2 on 2025-05-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('reader', 'Lector'), ('writer', 'Escritor'), ('content_creator', 'Creador de Contenido'), ('admin', 'Administrador')], default='reader', help_text='Rol del usuario que determina sus permisos en la plataforma', max_length=20),
        ),
    ]
